apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  selector:
    app: devsecops-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000